### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by n8fr8** [amoghbl1/Orfox#1] opened 2014-07-16 13:02 UTC
dnsleaktest.com shows a DNS leak with the current prototype build.

i think this is due to DNS resolution or InetAddress use in the Android UI code outside of GeckoView.

**Comment by amoghbl1** [comment] 2015-06-22 05:50
This is fixed with recent updates, also a duplicate of https://dev.guardianproject.info/issues/5238 . Updates to this shall be tracked there instead of here.

**Closed by amoghbl1** 2015-06-22 05:50 UTC
